#!/usr/bin/env python3
"""Build the final rerun_v2 computational-track closure document.

This script does not rerun simulations and does not recompute statistics. It
checks that the manuscript handover, final artifact index, README, and key
figure outputs are present, then writes a concise closure document for the
writing track.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class ClosureCheck:
    relative_path: str
    description: str
    required: bool = True


REQUIRED_PHRASES = {
    "docs/manuscript_results_handover.md": [
        "Mini heatmap synthesis",
        "Do not claim improved R&D performance",
        "Censored trajectories are not converted into artificial event times",
    ],
    "docs/final_artifact_index.md": [
        "Final artifact index",
        "Required artifacts missing: `0`",
        "Recommended manuscript package",
    ],
    "README.md": [
        "relational coordination readiness",
        "not R&D performance",
        "requirements.txt",
    ],
}


def default_checks() -> list[ClosureCheck]:
    return [
        ClosureCheck("README.md", "Repository-level reproducibility instructions"),
        ClosureCheck("requirements.txt", "Python dependency list"),
        ClosureCheck("docs/manuscript_results_handover.md", "Master computational handover"),
        ClosureCheck("docs/final_artifact_index.md", "Final artifact index"),
        ClosureCheck("figures/rerun_v2/mini_heatmap/mini_heatmap_rmst_heatmap.pdf", "Mini heatmap PDF"),
        ClosureCheck("figures/rerun_v2/mini_heatmap/mini_heatmap_rmst_heatmap.png", "Mini heatmap PNG"),
        ClosureCheck("figures/rerun_v2/mini_heatmap/mini_heatmap_rmst_heatmap_caption.txt", "Mini heatmap caption"),
    ]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def validate_required_phrases(repo_root: Path) -> list[str]:
    warnings: list[str] = []
    for rel_path, phrases in REQUIRED_PHRASES.items():
        path = repo_root / rel_path
        if not path.exists():
            warnings.append(f"PHRASE_CHECK_SKIPPED_MISSING_FILE: {rel_path}")
            continue
        text = read_text(path)
        for phrase in phrases:
            if phrase not in text:
                warnings.append(f"MISSING_REQUIRED_PHRASE: {rel_path} :: {phrase}")
    return warnings


def build_status_rows(repo_root: Path, checks: Iterable[ClosureCheck]) -> tuple[list[dict[str, str]], int]:
    rows: list[dict[str, str]] = []
    missing_required = 0

    for check in checks:
        path = repo_root / check.relative_path
        exists = path.exists()
        if check.required and not exists:
            missing_required += 1
        rows.append(
            {
                "path": check.relative_path,
                "description": check.description,
                "required": "yes" if check.required else "no",
                "status": "found" if exists else "missing",
            }
        )

    return rows, missing_required


def write_closure(repo_root: Path, output: Path, strict: bool) -> int:
    checks = default_checks()
    rows, missing_required = build_status_rows(repo_root, checks)
    phrase_warnings = validate_required_phrases(repo_root)

    output.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = []
    lines.append("# Computational track closure — rerun_v2")
    lines.append("")
    lines.append(f"Generated by `scripts/rerun_v2/build_computational_closure.py` on `{timestamp}`.")
    lines.append("")
    lines.append("## Closure status")
    lines.append("")
    if missing_required == 0 and not phrase_warnings:
        lines.append("**Status: closed for manuscript writing.**")
    elif missing_required == 0:
        lines.append("**Status: artifacts found, but phrase-check warnings remain.**")
    else:
        lines.append("**Status: not closed; required artifacts are missing.**")
    lines.append("")
    lines.append(f"Required artifacts missing: `{missing_required}`.")
    lines.append(f"Phrase-check warnings: `{len(phrase_warnings)}`.")
    lines.append("")

    lines.append("## Evidence base closed")
    lines.append("")
    lines.append("The rerun_v2 computational track is closed around six manuscript-facing evidence blocks:")
    lines.append("")
    lines.append("1. final core mechanism;")
    lines.append("2. translation-capability grid;")
    lines.append("3. boundary-spanner workload grid;")
    lines.append("4. mini heatmap synthesis;")
    lines.append("5. selection-rule robustness;")
    lines.append("6. readiness-threshold robustness.")
    lines.append("")

    lines.append("## Non-negotiable interpretation guardrails")
    lines.append("")
    lines.append("- The dependent variable is time to relational coordination readiness.")
    lines.append("- The results must not be interpreted as R&D performance, innovation success, patents, financial value, or output quality.")
    lines.append("- Censored trajectories are not converted into artificial event times.")
    lines.append("- RMST uses observed time `T_tilde`; event quantiles are reported only when estimable.")
    lines.append("- `agent_first` remains the baseline selection rule; `edge_uniform` is robustness.")
    lines.append("- The mini heatmap is a visual design map, not independently bootstrapped causal evidence.")
    lines.append("")

    lines.append("## Artifact closure table")
    lines.append("")
    lines.append("| Artifact | Role | Required | Status |")
    lines.append("|---|---|---:|---|")
    for row in rows:
        lines.append(f"| `{row['path']}` | {row['description']} | {row['required']} | {row['status']} |")
    lines.append("")

    lines.append("## Phrase-check warnings")
    lines.append("")
    if phrase_warnings:
        for warning in phrase_warnings:
            lines.append(f"- `{warning}`")
    else:
        lines.append("- None.")
    lines.append("")

    lines.append("## Recommended next step")
    lines.append("")
    lines.append("Move to the manuscript-writing track using `docs/manuscript_results_handover.md`, `docs/final_artifact_index.md`, and the figure/table outputs listed there as the computational source of truth.")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")

    if strict and (missing_required > 0 or phrase_warnings):
        return 1
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build rerun_v2 computational closure document.")
    parser.add_argument("--repo-root", default=None, help="Repository root. Defaults to two levels above this script.")
    parser.add_argument("--output", default=None, help="Output closure markdown file.")
    parser.add_argument("--strict", action="store_true", help="Fail if required artifacts or phrase checks are missing.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    script_path = Path(__file__).resolve()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else script_path.parents[2]
    output = Path(args.output).resolve() if args.output else repo_root / "docs" / "computational_track_closure.md"

    exit_code = write_closure(repo_root, output, strict=args.strict)

    print("\n============================================")
    print("RERUN V2 COMPUTATIONAL TRACK CLOSURE")
    print("============================================")
    print(f"repo_root: {repo_root}")
    print(f"output: {output}")
    if exit_code == 0:
        print("Computational closure document generated successfully.")
        print("RERUN V2 COMPUTATIONAL TRACK CLOSURE PASSED")
    else:
        print("Computational closure checks failed.")
    print("============================================")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
