function assert_same_ell1_path(g, f, tol, label)
% ASSERT_SAME_ELL1_PATH Test helper for generic/fast v0.7 equivalence.
  assert(isequaln(g.T,f.T) && g.delta==f.delta, ...
    'Fast/generic T mismatch in %s case.', label);
  assert(g.T_tilde==f.T_tilde && g.n_attempted==f.n_attempted, ...
    'Fast/generic stopping bookkeeping mismatch in %s case.', label);
  assert(g.n_served==f.n_served && g.n_blocked==f.n_blocked, ...
    'Fast/generic admission mismatch in %s case.', label);
  assert(isequaln(g.first_block_attempt,f.first_block_attempt), ...
    'Fast/generic first-block mismatch in %s case.', label);
  assert(g.n_windows_started==f.n_windows_started, ...
    'Fast/generic window-count mismatch in %s case.', label);
  assert(g.n_productive_A==f.n_productive_A && g.n_productive_B==f.n_productive_B, ...
    'Fast/generic productive-count mismatch in %s case.', label);
  assert(abs(g.WA-f.WA)<tol && abs(g.WB-f.WB)<tol && abs(g.Wmin-f.Wmin)<tol, ...
    'Fast/generic readiness mismatch in %s case.', label);
end
