function export_graph_summary_csv(GS, filename)
  % EXPORT_GRAPH_SUMMARY_CSV
  % Exports one row per graph realization.

  assert(isstruct(GS), 'GS must be a structure.');
  assert(ischar(filename), 'filename must be a character string.');

  fid = fopen(filename, 'w');

  assert(fid ~= -1, ...
    ['Could not open graph summary file: ', filename]);

  fprintf(fid, ['architecture,graph_id,n_trajectories,', ...
    'n_converged,n_nonconverged,convergence_rate,', ...
    'nonconvergence_rate,T_conv_mean,T_conv_median,', ...
    'T_conv_p90,T_conv_p95,T_cens_mean,T_cens_median,', ...
    'T_cens_p90,T_cens_p95,final_RB_mean,total_edges,', ...
    'mean_degree,max_degree,total_boundary_edges\n']);

  n_graphs = length(GS.graph_id);

  for g = 1:n_graphs
    fprintf(fid, ...
      ['"%s",%d,%d,%d,%d,%.10g,%.10g,', ...
       '%.10g,%.10g,%.10g,%.10g,', ...
       '%.10g,%.10g,%.10g,%.10g,', ...
       '%.10g,%.10g,%.10g,%.10g,%.10g\n'], ...
      GS.architecture, ...
      GS.graph_id(g), ...
      GS.n_trajectories(g), ...
      GS.n_converged(g), ...
      GS.n_nonconverged(g), ...
      GS.convergence_rate(g), ...
      GS.nonconvergence_rate(g), ...
      GS.T_conv_mean(g), ...
      GS.T_conv_median(g), ...
      GS.T_conv_p90(g), ...
      GS.T_conv_p95(g), ...
      GS.T_cens_mean(g), ...
      GS.T_cens_median(g), ...
      GS.T_cens_p90(g), ...
      GS.T_cens_p95(g), ...
      GS.final_RB_mean(g), ...
      GS.total_edges(g), ...
      GS.mean_degree(g), ...
      GS.max_degree(g), ...
      GS.total_boundary_edges(g));
  end

  fclose(fid);
end
