function export_combined_graph_summaries_csv(all_GS, filename)
  % EXPORT_COMBINED_GRAPH_SUMMARIES_CSV
  % Exports graph-level summaries from multiple architectures to one CSV.
  %
  % Input:
  %   all_GS    cell array of graph-summary structures
  %   filename  output CSV path

  assert(iscell(all_GS), 'all_GS must be a cell array.');
  assert(~isempty(all_GS), 'all_GS cannot be empty.');
  assert(ischar(filename), 'filename must be a character string.');

  fid = fopen(filename, 'w');

  assert(fid ~= -1, ...
    ['Could not open combined graph summary file: ', filename]);

  try
    fprintf(fid, ['architecture,graph_id,n_trajectories,', ...
      'n_converged,n_nonconverged,convergence_rate,', ...
      'nonconvergence_rate,T_conv_mean,T_conv_median,', ...
      'T_conv_p90,T_conv_p95,T_cens_mean,T_cens_median,', ...
      'T_cens_p90,T_cens_p95,final_RB_mean,total_edges,', ...
      'mean_degree,max_degree,total_boundary_edges\n']);

    for a = 1:length(all_GS)
      GS = all_GS{a};

      assert(isstruct(GS), ...
        'Each element of all_GS must be a structure.');

      n_graphs = length(GS.graph_id);

      for g = 1:n_graphs
        fprintf(fid, ...
          ['"%s",%d,%d,%d,%d,%.10g,%.10g,', ...
           '%.10g,%.10g,%.10g,%.10g,', ...
           '%.10g,%.10g,%.10g,%.10g,', ...
           '%.10g,%.10g,%.10g,%.10g,%.10g\n'], ...
          GS.architecture, ...
          GS.graph_id(g), ...
          GS.n_trajectories(g), ...
          GS.n_converged(g), ...
          GS.n_nonconverged(g), ...
          GS.convergence_rate(g), ...
          GS.nonconvergence_rate(g), ...
          GS.T_conv_mean(g), ...
          GS.T_conv_median(g), ...
          GS.T_conv_p90(g), ...
          GS.T_conv_p95(g), ...
          GS.T_cens_mean(g), ...
          GS.T_cens_median(g), ...
          GS.T_cens_p90(g), ...
          GS.T_cens_p95(g), ...
          GS.final_RB_mean(g), ...
          GS.total_edges(g), ...
          GS.mean_degree(g), ...
          GS.max_degree(g), ...
          GS.total_boundary_edges(g));
      end
    end

    fclose(fid);

  catch err
    fclose(fid);
    rethrow(err);
  end
end
